@base = http://127.0.0.1:4000
@content = Content-Type: application/json

POST {{base}}/comment http/1.1
{{content}}

{
  "path":"/comment.html",
  "name":"🤪",
  "email":"rainto0322@foxmail.com",
  "body":"这是一条测试",
  "pid":"67629043ea0762df1ecdf4de",
  "rid":"676290c45d276a925f429738"
}